import { db, Place } from "astro:db";

export default async function seed() {
  await db.insert(Place).values([
    {
      id: "1",
      name: "らーめん 鴨 to 葱",
      nameRoman: "Kamo to negi",
      address: "6 Chome-4-15 Ueno, Taito",
      gmaps: "https://maps.app.goo.gl/1ntouh3EjEs52RXy8",
      needsReserve: "",
      video: "https://www.instagram.com/p/C3nchNIv-lX/",
      website: "",
      tags: "ramen,duck",
      city: "Taitō",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "2",
      name: "中華そば 若葉",
      nameRoman: "Wakaba",
      address: "4 Chome-9-11 Tsukiji, Chuo",
      gmaps: "https://maps.app.goo.gl/bx5H73RxTAHnLZv46",
      needsReserve: "false",
      video: "https://www.instagram.com/p/C3OhpJkv6sy/",
      website: "",
      tags: "ramen,historical,light",
      city: "Chūō",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "3",
      name: "SLICE of LIFE",
      nameRoman: "",
      address: "4 Chome-21-13 Jingumae, Shibuya",
      gmaps: "https://maps.app.goo.gl/r4qnM6XFzScopRi57",
      needsReserve: "true",
      video: "https://www.instagram.com/p/C3yo8sGP24c/",
      website: "",
      tags: "wagyu,ribs,kokusan",
      city: "Shibuya",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "4",
      name: "有楽町かきだ",
      nameRoman: "Yuraku Chokakida",
      address: "2 Chome-2-1 Yoyogi, Shibuya, 19F",
      gmaps: "https://maps.app.goo.gl/eyB5oThqAiqNVqoQ6",
      needsReserve: "true",
      video: "https://www.instagram.com/p/C32dm1KhMbY/",
      website: "https://www.tablecheck.com/shops/yurakuchokakida/reserve",
      tags: "sushi,omakase",
      city: "Shibuya",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "5",
      name: "酒彩蕎麦 初代",
      nameRoman: "Shodai",
      address: "1 Chome−1−10, Ebisuminami, Shibuya 1F",
      gmaps: "https://maps.app.goo.gl/e5nW6RKc74b8CpMz6",
      needsReserve: "true",
      video: "https://www.instagram.com/p/C3puX_Dho-r/",
      website: "",
      tags: "curry,white,udon",
      city: "Shibuya",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "6",
      name: "Various ramen places",
      nameRoman: "",
      address: "Ogikubo",
      gmaps: "https://maps.app.goo.gl/BhFEoNFxhKxbfZG68",
      needsReserve: "false",
      video: "https://www.instagram.com/p/C3znFGSSDP-/",
      website: "",
      tags: "ramen",
      city: "Ogikubo",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "7",
      name: "ヤキニクマフィア",
      nameRoman: "Yakiniku Mafia",
      address:
        "〒171-0022 Tokyo, Toshima City, Minamiikebukuro, 1 Chome−26−6 YAKINIKUMAFIA IKEBUKURO The Sh One, 7F",
      gmaps: "https://maps.app.goo.gl/yRSVvTVtQsZDMVcx9",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C1soRU6vkVh/?igsh=YTRkeXk3dDJ1a3Iz",
      website: "https://yakinikumafia-ikebukuro.com/en/",
      tags: "ramen,wagyu",
      city: "Toshima",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "8",
      name: "いづも 池袋 うなぎ居酒屋",
      nameRoman: "Izumo",
      address: " 1 Chome-13-7 Nishiikebukuro, Toshima",
      gmaps: "https://maps.app.goo.gl/FJUx6RbxtpqhQ8FV9",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C37rgUkh-J3/?igsh=MTN0bDhxcGFtbDUweQ==",
      website: "https://tabelog.com/tokyo/A1305/A130501/13240206/",
      tags: "eel",
      city: "Toshima",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "9",
      name: "横浜くりこ庵 秋葉原店",
      nameRoman: "Kuriko An",
      address: "1 Chome−15−1, Sotokanda, Chiyoda",
      gmaps: "https://maps.app.goo.gl/AoW4trqif7nCTFna8",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C2QBNHAPVwA/?igsh=dHVqeWd0c2l3ZDAy",
      website: "",
      tags: "taiyaki,magikarp",
      city: "Chiyoda",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "10",
      name: "Various Street Food",
      nameRoman: "",
      address: "Shin-Ōkubo",
      gmaps: "https://maps.app.goo.gl/3cqXHzFWp8pnZEhK7",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C2u3Fi6ykIr/?igsh=MW9teXV6NWprenh1MA==",
      website: "",
      tags: "korean,street food",
      city: "Shin-Ōkubo",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "11",
      name: "銀座 八五",
      nameRoman: "Hachigo",
      address: "Chuo, Ginza, 3 Chome−14−2 第一はなぶさビル 1階",
      gmaps: "https://maps.app.goo.gl/a3t6eZUqPp6oAAPE9",
      needsReserve: "true",
      video:
        "https://www.instagram.com/reel/C02k4y4PNGR/?igsh=MXhvcmhiaWt0YjFxMg==",
      website: "",
      tags: "ramen,michelin star",
      city: "Chūō",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "12",
      name: "チームラボプラネッツ TOKYO DMM",
      nameRoman: "teamLab Planets",
      address: "6 Chome-1-16 Toyosu, Koto",
      gmaps: "https://maps.app.goo.gl/jfJUFxNops9RAq4d9",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C1F54aKvq51/?igsh=bW5lbWlrbDMyeWhr",
      website: "",
      tags: "ramen,miscellaneous",
      city: "Koto",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "13",
      name: "屋台ラーメン しゅんやっちゃん",
      nameRoman: "Shunyacchan",
      address: "1277-8 Hatsuzawamachi, Hachioji,",
      gmaps: "https://maps.app.goo.gl/fwN1mwdkVFFrarXs8",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C32TZj5SFvD/?igsh=MWNkZ3NndW9uc255NA==",
      website: "",
      tags: "ramen,street food",
      city: "Hachioji",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "14",
      name: "とんかつ 目黒 こがね",
      nameRoman: "Kogane",
      address: "1F Hirai Bld., 3-3-4 Kamiosaki, Shinagawa",
      gmaps: "https://maps.app.goo.gl/7GDufFNpzz9qHMQZ9",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C3VBQlZxole/?igsh=a3l2d2Frbnk0Y2dl",
      website: "",
      tags: "tonkatsu",
      city: "Shinagawa",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "15",
      name: "鉄板焼 摩天楼 東京スカイツリー・ソラマチ店",
      nameRoman: "Teppanyaki Matenrō",
      address: "Tokyo Sky Tree 31F (Soramachi)",
      gmaps: "https://maps.app.goo.gl/EuXhTCqEsKp9JEPw9",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3s7ZZyvZSD/?igsh=MWp4cjZ3N3AwejZxNw==",
      website: "",
      tags: "teppanyaki",
      city: "Sumida",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "16",
      name: "瑞兆",
      nameRoman: "Zuicho",
      address: "41-26 Udagawacho, Shibuya",
      gmaps: "https://maps.app.goo.gl/jbua6qQNVoa3TkDx8",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C3LmH-iBCTG/?igsh=N2FoM3o0dzg0YWM0",
      website: "",
      tags: "katsudon,cheap",
      city: "Shibuya",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "17",
      name: "AFURI",
      nameRoman: "",
      address: "Chain Restaurant",
      gmaps:
        "https://www.google.com/maps/search/Afuri/@35.6482946,139.7005726,15z/data=!3m1!4b1?entry=ttu",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C3-imGPxPlL/?igsh=MWdvZzF4NTJ0cG13cQ==",
      website: "",
      tags: "ramen,yuzu,chain",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "18",
      name: "Various Street Food",
      nameRoman: "",
      address: "Tsukiji Outer Market",
      gmaps: "https://maps.app.goo.gl/VqX6vpHvuo5RD3LMA",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C3BEoasxleI/?igsh=MjYxejh3MW50Mnpl",
      website: "",
      tags: "otoro,king crab,street food",
      city: "Chūō",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "19",
      name: "TOKYO PLACENTA 20cc",
      nameRoman: "",
      address: "Chuo, Ginza, 4 Chome−1−2",
      gmaps: "https://maps.app.goo.gl/iWpgjmRYb6pN9chD7",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C0nXesoS6cE/?igsh=MTN4bDdkMTY0bzV1aA==",
      website: "",
      tags: "placenta juice",
      city: "Chūō",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "20",
      name: "ふく吉",
      nameRoman: "Fukuyoshi",
      address: "1 Chome-7-2 Kamezawa, Sumida",
      gmaps: "https://maps.app.goo.gl/TLSTLHCZgvFtGrt37",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C326ftcvLQZ/?igsh=MWx1djV0ajdsMmlzdA==",
      website: "",
      tags: "sashimi,tenpura,cheap",
      city: "Sumida",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "21",
      name: "",
      nameRoman: "Ohno",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3rLXQiLCBy/?igsh=MWpkOXJzNTRrYW15dw==",
      website: "",
      tags: "gyudon,tamagodon",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "22",
      name: "",
      nameRoman: "Ichi Ni San",
      address: "Akiba",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3oNCGjvZNN/?igsh=MW9mNjExM2tvbHlnbg==",
      website: "",
      tags: "gyukatsu",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "23",
      name: "",
      nameRoman: "Forne",
      address: "Meguro",
      gmaps: "",
      needsReserve: "",
      video: "",
      website: "",
      tags: "pasta,pizza,mentaiko",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "24",
      name: "",
      nameRoman: "",
      address: "Asakusa",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3xKRUyS2nv/?igsh=MWtqYjBvZHpwZDIycg==",
      website: "",
      tags: "ramen,halal",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "25",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3zE1V4LtQm/?igsh=cG00czIxcDl1cXRo",
      website: "",
      tags: "tonkatsu",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "26",
      name: "",
      nameRoman: "Manma",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C2CTg94yt14/?igsh=NWJzNmNydDJneG04",
      website: "",
      tags: "onigiri",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "27",
      name: "",
      nameRoman: "",
      address: "Shinjuku",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3WBv5IS0s2/?igsh=ZDMzdXh4aW5wdHJv",
      website: "",
      tags: "nomihoudai",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "28",
      name: "",
      nameRoman: "",
      address: "Tokiwadai",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3uojLZyXwb/?igsh=bGMxcGo3MnlkNDhh",
      website: "",
      tags: "ramen,family",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "29",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C2hWZccyPSj/?igsh=cW5sbDZ0a205N3I=",
      website: "",
      tags: "sushi",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "30",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4F-CSEyhWL/?igsh=MXY4bmx5emF5ZWVpNQ==",
      website: "",
      tags: "tonteki",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "31",
      name: "",
      nameRoman: "",
      address: "Nakano",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4OAJyIrICz/?igsh=MWVxbWp6ZHJicWpzdw==",
      website: "",
      tags: "sushi",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "32",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4P_jqfS9he/?igsh=Zmpra2pxam5vaWZt",
      website: "",
      tags: "onigiri",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "33",
      name: "",
      nameRoman: "Monster Grill",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4P3VhfyU0o/?igsh=MTBzeTg2c3BtaHI5Mw==",
      website: "",
      tags: "meat",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "34",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4UiwS4rPEo/?igsh=MTc5eTJ4amt1ejk4Mw==",
      website: "",
      tags: "ramen,street food",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "35",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4OquHWInMG/?igsh=OHdtNGxvdnlmNDMz",
      website: "",
      tags: "okonomiyaki,family",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "36",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C4Kys9ByWAY/?igsh=MW44N2k1ZzI4OWVtYQ==",
      website: "",
      tags: "",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "37",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4jXSJiy5_0/?igsh=bmtqMnRlYTQ2MnE5",
      website: "",
      tags: "ramen,crab",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "38",
      name: "",
      nameRoman: "Utsuke",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4nOPBiSy1v/?igsh=cHp4dDJpdHh3M3pw",
      website: "",
      tags: "eel",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "39",
      name: "",
      nameRoman: "Horumon Takeda",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4h71OAS-v2/?igsh=Znd6bHJkMGpqdWZ3",
      website: "",
      tags: "yakiniku,tabehoudai",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "40",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4K2KI5PETF/?igsh=MXJ1cmtvZmh6M3dzaw==",
      website: "",
      tags: "tsukemen",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "41",
      name: "PERFECT BEER KITCHEN 総本店",
      nameRoman: "Monnaka",
      address: "14-2 Fuyuki, Koto",
      gmaps: "https://maps.app.goo.gl/NcwmAmySZmXXEK9U8",
      needsReserve: "false",
      video: "https://www.instagram.com/perfect_beer_kitchen_tokyo/",
      website: "",
      tags: "beer",
      city: "Koto",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "42",
      name: "",
      nameRoman: "Kitsuneya",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4h2i2SSOh1/?igsh=MXcxbXZsNmpjeGgwag==",
      website: "",
      tags: "gyudon",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "43",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3PnyYzy5_p/?igsh=aG1kaXg1c2ljcjl0",
      website: "",
      tags: "sushi,tuna",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "44",
      name: "",
      nameRoman: "Shinjuku",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3H0Vf_S7u-/?igsh=aXd4Yjlhbm5xODA3",
      website: "",
      tags: "sushi,tabehoudai",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "45",
      name: "",
      nameRoman: "Sugita",
      address: "",
      gmaps: "",
      needsReserve: "true",
      video:
        "https://www.instagram.com/reel/C3jR3OasoEB/?igsh=MTR0YnhzdWI4d2xrZQ==",
      website: "https://omakase.in/en/r/fa131638",
      tags: "sushi,top1",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "46",
      name: "",
      nameRoman: "Fuumji",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4dkIKby1ZW/?igsh=bTRxbm13eGVmZm4x",
      website: "",
      tags: "ramen,dip",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "47",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C5JPOOLyowM/?igsh=YnJ5emVjc2tqenF4",
      website: "",
      tags: "curry,chicken",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "48",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C5jmzyIyPKR/?igsh=a25uM2wyZ3FncTZo",
      website: "",
      tags: "sashimi",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "49",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C6fL81gxUd3/?igsh=Z29naGQyM2JidWw0",
      website: "",
      tags: "ramen,crab",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "50",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C63lZ7ZsRnP/?igsh=MjN3ZTgzdWZhYmhr",
      website: "",
      tags: "curry,special",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "51",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C7PTCqcvpEi/?igsh=M2NjOTh6aGRiazV1",
      website: "",
      tags: "sushi,cheap",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "52",
      name: "",
      nameRoman: " Naraya",
      address: "Ikebukuro",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C74aiv2PzPb/?igsh=c3J5MTMxcGRzMDFp",
      website: "",
      tags: "soba",
      city: "Ikebukuro",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "53",
      name: "",
      nameRoman: "Komagomeya",
      address: "Komagome",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C8pQ_RXvi-H/?igsh=N2VsMmk4bWpudHN3",
      website: "",
      tags: "ramen,iekei",
      city: "Toshima",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "54",
      name: "",
      nameRoman: "Andra",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C8_z28YSuLY/?igsh=d2trem81aWNzY3M2",
      website: "",
      tags: "burger",
      city: "",
      state: "Tōkyō",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "55",
      name: "鉄板焼き ゑびす",
      nameRoman: "Teppanyaki Yebisu",
      address: "1 Chome-1-10 Nanbanaka, Naniwa",
      gmaps: "https://maps.app.goo.gl/5tUksejctdHcwsoTA",
      needsReserve: "true",
      video: "https://www.instagram.com/p/C3zrewIvump/",
      website: "",
      tags: "teppanyakik,wagyu,black wagyu",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "56",
      name: "焼肉結局たれ。梅田店",
      nameRoman: "Kekkyokutare",
      address: "Doyamacho, 10−16 1F, Kita",
      gmaps: "https://maps.app.goo.gl/1Z6fQfZzphQApuYH6",
      needsReserve: "true",
      video: "https://www.instagram.com/p/C3r-bSQPCj2/",
      website: "https://osaka-chaozu.com/access/tare/",
      tags: "wagyu,black,tabehoudai",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "57",
      name: "花丸軒 法善寺店",
      nameRoman: "Hanamaruken ",
      address: "1 Chome-2-1 Namba, Chuo",
      gmaps: "https://maps.app.goo.gl/ob8DNBT3Vng3wuoZA",
      needsReserve: "false",
      video: "https://www.instagram.com/p/C3oJAqdvvss/",
      website: "",
      tags: "ramen,24h",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "58",
      name: "さかえすし 玉屋町店",
      nameRoman: "Sakae",
      address: " 2-27 Souemoncho, Chuo",
      gmaps: "https://maps.app.goo.gl/wcc2ZjAfr1JxBYYF9",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C1u65e6ywFe/?igsh=amNrbjNmbGRmdnZz",
      website: "",
      tags: "sushi",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "59",
      name: "",
      nameRoman: "Goku",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3Mwdrgiidg/?igsh=dmxtZDU5Y3AxdjNu",
      website: "",
      tags: "ramen",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "60",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C2pdKj-vBtD/?igsh=N2d1YW1iMHM1aHBn",
      website: "",
      tags: "",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "61",
      name: "",
      nameRoman: "Gorichan",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4A3MFRR2BN/?igsh=MXV5eTlnbHl4bHI5",
      website: "",
      tags: "onigiri",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "62",
      name: "",
      nameRoman: "Mugito Mensuke",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3ksvvDhhS1/?igsh=YzB2d3o3eDl4aHh1",
      website: "",
      tags: "ramen",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "63",
      name: "",
      nameRoman: "Sandaime wakihiko shouten",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C0_p7sgvAke/?igsh=NjVsNDdxc2g2d3Vu",
      website: "",
      tags: "wagyu",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "64",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4AmcFkPPjf/?igsh=MWpkamxlaWEzbzYxOQ==",
      website: "",
      tags: "sukiyaki",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "65",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3cCNgZL2iF/?igsh=MW15NTIydnptd3J5dA==",
      website: "",
      tags: "tonkatsu,sando,giant",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "66",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C24TGYoLKFi/?igsh=bHVjenR2cjB1Y3Ri",
      website: "",
      tags: "tonkatsu,sando,giant",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "67",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C34yMaGPLP-/?igsh=ZmdhdDlldXV0em0w",
      website: "",
      tags: "yakiniku",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "68",
      name: "",
      nameRoman: "",
      address: "Honmachi",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3rVTB8SMfU/?igsh=MXh1dzlqOW8xemhpaA==",
      website: "",
      tags: "prawn,giant",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "69",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3G6rIkyRLm/?igsh=anU4MXpjNnF0NGx3",
      website: "",
      tags: "onigiri,street food",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "70",
      name: "Sanpei",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C29VfW8PQad/?igsh=ejA4YzFoeG5ndWR4",
      website: "",
      tags: "okonomiyaki",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "71",
      name: "Kozou",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3-JmYJPr5n/?igsh=Y3Z6OWkzNGJzNGhr",
      website: "",
      tags: "ramen,giant",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "72",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3Kvc8_PV5V/?igsh=MXA0dnJtdGtjdWFqNw==",
      website: "",
      tags: "takoyaki",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "73",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C1ViPl5PLGD/?igsh=N2g4Z2x1ZnFsZXE0",
      website: "",
      tags: "onigiri,giant",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "74",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C1z9XCAy6DX/?igsh=OWI3MTVoc2p3dm5h",
      website: "",
      tags: "curry",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "75",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4C7OsoS7JM/?igsh=MTVnbXY5a2xkaG5oYQ==",
      website: "",
      tags: "yakiniku",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "76",
      name: "",
      nameRoman: "Nikusho Nakata",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4SHEamyLOv/?igsh=emNzazQ1bTBrMmE5",
      website: "",
      tags: "yakiniku,pro",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "77",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4Kpr1av2h7/?igsh=MXBoMDdyeDF1NTcwNA==",
      website: "",
      tags: "wagyu",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "78",
      name: "",
      nameRoman: "Gorichan",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4m8A1qLxIZ/?igsh=Z2Nsb2I2MWZ1MjM=",
      website: "",
      tags: "onigiri",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "79",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4t7nXFyrSD/?igsh=a2U0eXo5aTV4czJx",
      website: "",
      tags: "sushi,omakase",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "80",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4rLsMTvZN9/?igsh=MWk5N3M1a2JreWxyaw==",
      website: "",
      tags: "dim sum",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "81",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C3pO5QXS3Wn/?igsh=MWZyYmNqenBzYWIwYQ==",
      website: "",
      tags: "ramen,jiro,pro",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "82",
      name: "",
      nameRoman: "Rocket Kaihatsu",
      address: "〒665-0035 兵庫県宝塚市 逆瀬川1丁目8-22",
      gmaps: "",
      needsReserve: "false",
      video:
        "https://www.instagram.com/reel/C7bpua5sxtY/?igsh=b3p6a3NkaDcxMnh3",
      website: "",
      tags: "ramen,mapo toufu,slow-cooked",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "83",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C6vhCYmx_1O/?igsh=NmxtNGVxamp3b2k5",
      website: "",
      tags: "meat,giant",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "84",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C8CjYI4vKVZ/?igsh=ZnNpazZkMTU2bndx",
      website: "",
      tags: "wagyu",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "85",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C89e6OapmE1/?igsh=MXQ0cXh0N3pydmVmMg==",
      website: "",
      tags: "ramen,cheese",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "86",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C6s3MRzy7Z1/?igsh=MXQ2amJlOHg2ejdvZQ==",
      website: "",
      tags: "rice,giant",
      city: "Ōsaka",
      state: "Ōsaka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "87",
      name: "焼肉ぽんが 江ノ島店",
      nameRoman: "Ponga",
      address: "Fujisawa, Katasekaigan, 2 Chome−18−17 ３",
      gmaps: "https://maps.app.goo.gl/tKgvwt6KwKDCBza66",
      needsReserve: "",
      video: "https://www.instagram.com/p/C3J7E8yBRLv/",
      website: "",
      tags: "yakiniku,wagyu",
      city: "",
      state: "Kanagawa",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "88",
      name: "",
      nameRoman: "Burger King",
      address: "-",
      gmaps: "",
      needsReserve: "false",
      video: "https://www.instagram.com/p/C3FonswSY9_/",
      website: "",
      tags: "burger,giant,seasonal",
      city: "",
      state: "All",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "89",
      name: "",
      nameRoman: "Gourmet",
      address: "-",
      gmaps: "",
      needsReserve: "true",
      video: "https://www.instagram.com/p/C3xPnl4yN9X/",
      website: "",
      tags: "sushi",
      city: "",
      state: "All",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "90",
      name: "",
      nameRoman: "Kichikichi",
      address: "",
      gmaps: "",
      needsReserve: "true",
      video:
        "https://www.instagram.com/reel/C0pIJXIgeIm/?igsh=ZW5ydG1haTFsYTZt",
      website: "",
      tags: "omurice",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "91",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C06tjDyrFmr/?igsh=bmhvYnRxb295NzFh",
      website: "",
      tags: "",
      city: "",
      state: "Kōbe",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "92",
      name: "",
      nameRoman: "Kuramaki Bunecho",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C2o_fx5vXt9/?igsh=MXU4NGE3cTFhb2RpOQ==",
      website: "",
      tags: "soumen,bamboo",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "93",
      name: "",
      nameRoman: "Menya Takakura Nijo",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C1oIM9qsieZ/?igsh=M3lkYTN5bXVxejJr",
      website: "",
      tags: "ramen,yuzu",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "94",
      name: "",
      nameRoman: "Fuki Paozuro",
      address: "Yokihama",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4EjxGxyUzr/?igsh=dzd0NTFjZHZzYmFi",
      website: "",
      tags: "skewer,dim sum",
      city: "",
      state: "Kanagawa",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "95",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3jONMWhFnM/?igsh=MWZjMXhhZnh0YjV1aw==",
      website: "",
      tags: "gyunabe",
      city: "",
      state: "Hakone",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "96",
      name: "",
      nameRoman: "Varios",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C36bfwTRQ3L/?igsh=NjZxeWk2cnNhZjN6",
      website: "",
      tags: "",
      city: "",
      state: "Nagoya",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "97",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3-bQ-gyU4C/?igsh=YnVwcWFvbDRybmo=",
      website: "",
      tags: "udon",
      city: "",
      state: "Kagawa",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "98",
      name: "",
      nameRoman: "Taberogu",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C343_9eywTI/?igsh=MW05Z2oxb3U0MHU5bw==",
      website: "",
      tags: "",
      city: "",
      state: "All",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "99",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3eE_kUuDwZ/?igsh=MXQ1amJzMjNrMmV5Yw==",
      website: "",
      tags: "breakfast,tabehoudai",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "100",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C2msY9pPp12/?igsh=Y3dvNW1xZTZyeXl1",
      website: "",
      tags: "soy sauce,traditional",
      city: "",
      state: "",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "101",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3KUH27SBID/?igsh=bTRiMHVybzN4cWJm",
      website: "",
      tags: "ramen",
      city: "",
      state: "Fukuoka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "102",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C06RYOayFdX/?igsh=dGFva3J6ZXR1M2k4   https://www.instagram.com/reel/C4C-f9IJ87b/?igsh=MWJ2ZDRnajdwNTFicw==",
      website: "",
      tags: "ramen,flame",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "103",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4WoDxnyMoA/?igsh=MWRnbnVibTEydmV5Mg==",
      website: "",
      tags: "karaage",
      city: "",
      state: "Yokohama",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "104",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4aATf5LSkV/?igsh=MWNlaGtmcHd0aGpxeQ==",
      website: "",
      tags: "yakiniku,wagyu",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "105",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4j-_JFveAc/?igsh=MWpyZHA3MXRkNW42Zw==",
      website: "",
      tags: "wagyu,street food",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "106",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4X3AixS2mw/?igsh=MzVkYjFlMG5tdTlj",
      website: "",
      tags: "wok,flame",
      city: "",
      state: "Fukuoka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "107",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3KMNmhyQ3j/?igsh=cmQ5a202bnV1NWpw",
      website: "",
      tags: "tuna",
      city: "Kawaguchi",
      state: "Saitama",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "108",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3Mwxp8vKTO/?igsh=MTN0bjc2OXNwYm5qcQ==",
      website: "",
      tags: "tuna",
      city: "",
      state: "Chiba",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "109",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C3r9k7MSgMz/?igsh=MXUxM3UzcTU2aGd3Yg==",
      website: "",
      tags: "katsudon,giant,pork belly",
      city: "",
      state: "",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "110",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C2H93eISMvu/?igsh=MWk2OHA4Nmtwb2QyZA==",
      website: "",
      tags: "ranch",
      city: "",
      state: "Shizuoka",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "111",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C4xC9BNPn1u/?igsh=Y3psMWI0a2wyNXgw",
      website: "",
      tags: "mochi",
      city: "",
      state: "",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "112",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C2vhLy7v4lw/?igsh=cXhmcjNvd3F2NXI=",
      website: "",
      tags: "yuba",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "113",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C5XFPZQv9Kk/?igsh=MTZoMmk4aHhhbHU2dw==",
      website: "",
      tags: "sukiyaki",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "114",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C5ZQYkcymsy/?igsh=NTU1YnppM2x3ZnUw",
      website: "",
      tags: "ramen",
      city: "",
      state: "Kyōto",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "115",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C7UAin1vnj0/?igsh=ZWNsNTRrdjJ6ZXpo",
      website: "",
      tags: "gyoza",
      city: "",
      state: "Takayama",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "116",
      name: "まんぷく家 井田248店",
      nameRoman: "Manpukuya",
      address: "2-2 Ida Minamimachi, Okazaki, Aichi 444-0068",
      gmaps: "https://maps.app.goo.gl/VbWJCJwDjspwBKMM8",
      needsReserve: "",
      video: "",
      website: "https://www.manpukuya.jp/",
      tags: "ramen,iekei",
      city: "Okazuki",
      state: "Nagoya",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "117",
      name: "町田商店 横浜駅前店",
      nameRoman: "Machida Shoten Yokohama Ekimae",
      address:
        "2 Chome-19-3 Tsuruyacho, Kanagawa Ward, Yokohama, Kanagawa 221-0835",
      gmaps: "https://maps.app.goo.gl/RMXTEuwbt389paVK8",
      needsReserve: "",
      video: "",
      website: "https://shop.machidashoten.com/japan/detail/111003/",
      tags: "ramen,iekei",
      city: "Kanagawa",
      state: "Yokohama",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "118",
      name: "",
      nameRoman: "Dailan Honten",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C9AFtZrpg6R/?igsh=MTY4MW90bWtlbnV0aQ==",
      website: "",
      tags: "ramen,oldest",
      city: "Amagasaki",
      state: "Hyōgo",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "119",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C8USAAGKmJb/?igsh=NDgybXRmZGtodmxx",
      website: "",
      tags: "ramen,katsuo",
      city: "Makurazaki",
      state: "Kagoshima",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "120",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C8J_lQFsgTh/?igsh=NnczMTZqbHl4eTl2",
      website: "",
      tags: "curry",
      city: "Amagasaki",
      state: "Hyōgo",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "121",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C9SFQCIh1Rh/?igsh=ZXVjcmd5cndsNDl6",
      website: "",
      tags: "ramen,pineapple",
      city: "",
      state: "",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "122",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C6gMVXgvUiT/?igsh=b2gwY3RsNW9qYzhq",
      website: "",
      tags: "7-11",
      city: "",
      state: "",
      country: "Japan",
      review: "",
      rating: "",
    },
    {
      id: "123",
      name: "",
      nameRoman: "",
      address: "",
      gmaps: "",
      needsReserve: "",
      video:
        "https://www.instagram.com/reel/C97BoeMx5zj/?igsh=MXQ0eXhlanMyZjQ5Nw==",
      website: "",
      tags: "soba",
      city: "Gifu",
      state: "Gifu",
      country: "Japan",
      review: "",
      rating: "",
    },
  ]);
}
